-- Rows in every table (poster Table 4, first check).
-- UNION ALL stacks the nine one-row results into one table.
SELECT 'LOCATION'          AS table_name, count(*) AS row_count FROM LOCATION
UNION ALL SELECT 'WEATHER_STATION',   count(*) FROM WEATHER_STATION
UNION ALL SELECT 'WEATHER_DATA',      count(*) FROM WEATHER_DATA
UNION ALL SELECT 'AQI_CATEGORY',      count(*) FROM AQI_CATEGORY
UNION ALL SELECT 'APP_USER',          count(*) FROM APP_USER
UNION ALL SELECT 'REGION_FORECAST',   count(*) FROM REGION_FORECAST
UNION ALL SELECT 'REGION_WARNING',    count(*) FROM REGION_WARNING
UNION ALL SELECT 'WARNING_THRESHOLD', count(*) FROM WARNING_THRESHOLD
UNION ALL SELECT 'INGESTION_RUN',     count(*) FROM INGESTION_RUN;
